### PR TITLE
Heatindex efficiency

### PR DESCRIPTION
**Pull request by finitespace**
This fixes issue #63 and extends pull #65.

@jirkaptr @coelner  please review this pull before I merge it to master.

### CODE REVIEW

**Comment by coelner** [comment]
@jirkaptr Did you only test for ATMEGA328?

**Comment by jirkaptr** [comment]
Yes, savings 162B FLASH/60usec were achieved at ATMEGA328/16MHz using a standard compiler  of ARDUINO IDE 1.6/1.9. These savings represent 12% of HeatIndex() volume before optimization. 
Other processors, compilers or other than default compiler settings were not tested.

BTW @finitespace, merging the pull request, pls increase the version number especially in library.properties file. Otherwise, updates will not be offered in the IDE's Library manager.

**Comment by coelner** [comment]
IMHO we should write a generic library without using optimized code for a specific platform.

**Comment by finitespace** [comment]
@jirkaptr the version number gets increased when I make an official release. Once it is tagged it will show up in the library manager. I am holding off on 3.0 because the interface is changing still.

**Comment by finitespace** [comment]
I actually agree with @coelner. The code should be readable, over, optimized. I am not going to support optimized code for separate platforms. So, after thinking about it, if you would like to optimized code for an architecture, you should fork the project and do it on your own branch. I agree with reducing waste in the code, but the code should still be readable.

**Comment by jirkaptr** [comment]
I believe that the compressed formula is appropriate. The issue can be viewed from two points of view. 

 

·         Coelner’s objection inspired me to test the compressed formula on all Arduino AVR boards listed in VS/VM and in Arduino IDE, ie. on the ATmega 168, 32u4, 328, 2560 processors. Not surprisingly, the result was always the same up to a small deviation of 2560 because all listed microcontrollers  have the 8-bit ALU and practically the same instruction code.  

 

·         Compiler is used in the VS/VM default code optimization setting. I, as a programmer, just chose the calculation sequence to minimize the number of mathematical operations and movement of intermediate results. It has really happened: instead of 15 multiplications of float point numbers we have only 8 ones.  This method is completely versatile and brings an analogous effect on any platform. BTW RobTillaart has designed a very similar compression - see http://forum.arduino.cc/index.php?topic=107569.0 (response #2).

**Comment by coelner** [comment]
Maybe we should specify which optimization we prefer. @finitespace prefer understandable readable over optimized code, because we design a generic library. @jirkaptr however get from a architecture optimized formula to a more generic solution. 

1. it is a library for embedded devices
2. therefore we should optimize formula based on a mathematical view to reduce calculation work in general
3. we could use http://wolframalpha.com to get an easy documentation how we get to this formula

E.g.:
http://www.wolframalpha.com/input/?source=nav&i=b%3D+x1+%2B+x2*T+%2B+x3*H+%2B+x4*T*H+%2B+x5*T*T+%2B+x6*H*H+%2B+x7*T*T*H+%2B+x8*T*H*H+%2B+x9*T*T*H*H

**Comment by jirkaptr** [comment]
Embedded devices often suffer from a limited amount of program and data memory. Here the code efficiency should be preferred.

The clarity of the solution can be achieved by comment containing the link to the complete description of the algorithm (http://www.wpc.ncep.noaa.gov/html/heatindex_equation.shtml  and/or  https://ehp.niehs.nih.gov/1206273/) or as minimum a reference to the heat-index definition (e.g. https://en.wikipedia.org/wiki/Heat_index ).

Everyone will be satisfied.

**Comment by finitespace** [comment]
I am fine leaving it optimized if everyone agrees and there is good documentation. 

I have been very busy recently and haven't had anytime to look at this. Would one of you like to add the necessary documentation, including a link, short description and explanation?

**Comment by jirkaptr** [comment]
I prefer the documentation should be created by @coelner because the HeatIndex and AbsoluteHumidity extensions were initiated and carried out by him. My role was only advisory. Also the level of my English is not sufficient for that task ...

**Comment by coelner** [comment]
Ok, I'm fine with that. But I need some days to finish it.

**Comment by finitespace** [comment]
Resolved #65

**Pull request closed without merging**
