### PR TITLE
altitude() formula replaced, calculations made units-proof, comments extended

### LINKED ISSUE #44: Altitude calculation formula
The used formula is very simple, but very inaccurate, usable for rough calculation. Much better results are provided by two variants of the calculation in http://drkfs.net/correctiontosealevel.htm.   The Laplace’s formula is very versatile, while the Babinet’s formula is a good compromise of precision and simplicity.
The auxiliary value e/b can be derived e.g. in http://www.weather.gov/media/epz/wxcalc/vaporPressure.pdf.

### PR DESCRIPTION
**Pull request by jirkaptr**
- altitude() formula replaced by inversion of equivalentSeaLevelPressure() formula because it is more accurate.  It resolves #44 issue. 

- All calculating functions may be supplied by parameters in any units now. (°C, °F, meters, feets, hPa, Pa...)

- Calculating functions can handle NAN input values now.

- README.md actualized in this way.

### CODE REVIEW

**Comment by finitespace** [comment]
EnvironmentalCalculations.h/cpp show you removed all lines and added all lines. I would like it to show the actual line changes. Do you know what caused this? We might need to redo the pull. I am anal about this, I have been burned a lot by it in the past.

**Comment by finitespace** [comment]
For outdoorTemp, if you have a station indoor, would you use the indoor temp? Keep in mind this library is used for indoor monitoring as well and mobile applications. Perhaps this should be renamed to external temp or just temp. Are you trying to distinguish between an internal unit temp and and external temp or do you actually mean the outdoor temp regardless of unit location?

**Comment by finitespace** [comment]
Sorry for all the individual comments. Can you also please submit this pull request against the Version 3.0.0 branch? The version 2.3.0 branch is to support backward compatibility before the 3.0.0 transition and is a dead branch.

**Comment by jirkaptr** [comment]
All calculations are based on the natural sciences laws of regarding hydrostatic pressure – barometric formula (B. Pascal) and the theory of atmosphere (Laplace’s formula). Individual applications formulas differ in a level of simplification of calculations or in fine differences of constants. The World Meteorological Organization (WMO)   does not define binding rules, but it describes on 20 pages the variability of the Laplace’s equation use in 107 member countries – see [https://library.wmo.int/opac/doc_num.php?explnum_id=344](https://library.wmo.int/opac/doc_num.php?explnum_id=344). The Swedish document https://www.wmo.int/pages/prog/www/IMOP/meetings/SI/ET-Stand-1/Doc-10_Pressure-red.pdf is interesting due to likely ironic description of calculation methods used in Scandinavia.
However **in any case the calculation of altitude/height and pressure takes in account the features of ambient atmosphere – primarily temperature and its gradient, next are humidity, gravity…** Because the exact description of atmosphere is impossible, **there are simplifying assumptions**. **The first is the use of International Standard Atmosphere (ISA) properties, i.e. the temperature at sea level is 15°C, the air is dry, etc.** Here are used QNH, QNE concerning mainly aviation. The approaching aircraft pilot will get the landing values valid at a given moment on the landing surface to properly adjust the altimeter. 
Similarly, in the case of mountain tourism, paragliding, height measurement: If changes of pressure reduced to MediumSeaLevel (QNH, QFF) may be neglected during the trip and the height difference is not too big (temperature rate may be neglected), it is advisable to calibrate the altimeter at the starting point (set the height = 0) and derive the instant height of barometer from the calibrated value.
Another option is **the use for meteorological measurements** (QFE and QFF). **We need at least a real temperature at the measuring point, and it is also advisable to know the real humidity (in the case of more accurate formula) of the air. The parameters of the air-conditioned room are not correct for this purpose.**
It is not possible to explain it in few sentences. Look for keywords Atmospheric pressure, Barometric formula, Laplace formula, altimeter setting etc.

**Comment by jirkaptr** [comment]
My modifications were derived from "Merge pull request #52 from finitespace/3.0.0-rc.1" For example the file library.properties contains the text "version=3.0.0". I guess it is your last version. Maybe I'm wrong?

Sorry for the confusion with EnvironmentalCalculations.h/cpp. I failed to set correctly the path to library of forked project (in fact the forked folder itself) in VS2015. (any advice?) In the end I by-passed the almost finished files to src without knowing what Github would do with it. (This is my first contribution into github.) Unfortunately, I can't selectively change these 2 files. Maybe I had to do everything from the beginning again. Shall you kind to compare files with other means? It is approx. 150 lines...

**Comment by finitespace** [comment]
Your checkout was against the 3.0.0-rc.1 branch. Your pull request, however, is against the 2.3.0 branch. I can fix the files for you. I will fork your branch, fix the files and then submit another pull request against 3.0.0-rc .1. 

Great explanation on the temp, so it is in fact the outdoor ambient temperature. I just wanted to make sure before people started asking.

**Comment by jirkaptr** [comment]
Thank for the help. What cooperation do you need from me? How can I help you? J.

**Comment by finitespace** [comment]
It looks like you also got some visual studio files in there and deleted them, so branching will be good.

Alright, here is what I need you to do.  Changing `<summary of commits>` to a summary of your summary, paste the following into a terminal:

```
git clone https://github.com/jirkaptr/BME280 altitude
cd altitude
git branch altitude 3e04e7be953b431cb281b36afdfbdce38129185c
git checkout altitude

git show master:src/EnvironmentCalculations.h >src/EnvironmentCalculations.h
git show master:src/EnvironmentCalculations.cpp >src/EnvironmentCalculations.cpp
git show master:examples/Environment_Calculations/Environment_Calculations.ino >examples/Environment_Calculations/Environment_Calculations.ino
git show master:README.md >README.md

git commit src/EnvironmentCalculations.h src/EnvironmentCalculations.cpp examples/Environment_Calculations/Environment_Calculations.ino -m '<summary of commits>'
git push origin altitude
```

**Comment by jirkaptr** [comment]
Please confirm the procedure:

1. I have only used direct access in Github and VisualStudio. => I need to download and install Git (offered in https://git-scm.com/downloads)  to be able enter the sequence  of git commands

2. Enter step by step the sequence of git commands as mentioned before.

3.Rreport in some way the termination of the operation.

Is it correct?

 

Od: finitespace [mailto:notifications@github.com] 
Odesláno: úterý 28. listopadu 2017 10:54
Komu: finitespace/BME280
Kopie: jirkaptr; Author
Předmět: Re: [finitespace/BME280] altitude() formula replaced, calculations made units-proof, comments extended (#53)

 

It looks like you also got some visual studio files in there and deleted them, so branching will be good.

Alright, here is what I need you to do. Changing <summary of commits> to a summary of your summary, paste the following into a terminal:

git clone https://github.com/jirkaptr/BME280 altitude
cd altitude
git branch altitude 3e04e7be953b431cb281b36afdfbdce38129185c
git checkout altitude
 
git show master:src/EnvironmentCalculations.h >src/EnvironmentCalculations.h
git show master:src/EnvironmentCalculations.cpp >src/EnvironmentCalculations.cpp
git show master:examples/Environment_Calculations/Environment_Calculations.ino >examples/Environment_Calculations/Environment_Calculations.ino
git show master:README.md >README.md
 
git commit src/EnvironmentCalculations.h src/EnvironmentCalculations.cpp examples/Environment_Calculations/Environment_Calculations.ino -m '<summary of commits>'
git push origin altitude

**Comment by jirkaptr** [comment]
Everything is done. here is a protocol: 
[protocol.txt](https://github.com/finitespace/BME280/files/1510010/protocol.txt)

**Comment by finitespace** [comment]
Everything looks good except you did not replace '<summary of commits>' with your own comment. 

That's fine though, that is not as important, can you submit to this thread a short paragraph 1-2 sentences with a summary of your commits for this pull. Then instead of making you redo this (if you would like to redo it you can replace altitude with altitude-1 and change your final commit comment) I will add your commit description to the pull request when I merge with trunk. 

Also, please make sure the code still runs after the above procedure.

Thanks for contributing!

**Comment by jirkaptr** [comment]
* altitude() formula replaced by inversion of equivalentSeaLevelPressure() formula because it is more accurate. It resolves #44 issue.
* All calculating functions may be supplied by parameters in any units now. (°C, °F, meters, feets, hPa, Pa...)
* Calculating functions can handle NAN input values now.
* README.md actualized in this way.
* Tested with all types of units.

**Comment by jirkaptr** [comment]
EnvironmentCalculations use hPa as default units, while the basic functions are preset to Pa (BME280.h, README).  In order to avoid confusion for users, I recommend to set all default values in hPa, because just hPa unit is used preferably.
Should I do it in BM280.h and README? (To add "h" to a total about 4 + 4 places.)

**Comment by finitespace** [comment]
Yes, that is fine if you want to do that.

**Comment by jirkaptr** [comment]
Already done in altitude (sub?)branch.

**Comment by finitespace** [comment]
Perfect, I got bogged down, but I plan to merge this tomorrow.

**Pull request closed without merging**
