### PR TITLE
Heatindex

### PR DESCRIPTION
**Pull request by coelner**
#64 #63 
for enhancing the formula see here: https://en.wikipedia.org/wiki/Heat_index 
or this one: http://www.bom.gov.au/info/thermal_stress/#apparent

feel free to implement

### CODE REVIEW

**Comment by finitespace** [comment]
Why did you change Nan to -1? I would prefer Nan.

**Comment by finitespace** [comment]
@jirkaptr does this satisfy?

**Comment by finitespace** [comment]
I have merged HappyWheels fix for the semi-colon in the interim, while we figure this out. Please make sure your code compiles before submitting a pull request.

**Comment by finitespace** [comment]
This pull request needs to be re-done. I can't tell what it going on. It also appears you are overriding some of the changes I made after merging your last code.

**Comment by finitespace** [comment]
Is there no longer a requirement for the temp being above 80F? The documentation in the .h file was not updated, but that seems to have been removed everywhere else.

**Comment by coelner** [comment]
@finitespace @jirkaptr #77 any annotations?

**Comment by jirkaptr** [comment]
My brief observations and remarks:

**- EnvironmentCalculations.h regarding HeatIndex():**
The comment
„_///The formula based on the Heat Index Equation of the US National Weather Service
  /// http://www.wpc.ncep.noaa.gov/html/heatindex_equation.shtml“_
is no more correct.
I recoomend to use the links as follows (copied from EnvironmentCalculations.cpp) :  
_https://ehp.niehs.nih.gov/1206273/ and in detail this flow graph: https://ehp.niehs.nih.gov/wp-content/uploads/2013/10/ehp.1206273.g003.png_  

**- Readme.md regarding HeatIndex:**
The idea „The U.S. NWS algorithm is used.“ is incorrect now. Again use the above recommended comment.

**- EnvironmentCalculations.cpp regarding  HeatIndex():**
The  comment 
„_/* Check the correctness with the following link:
       http://www.wolframalpha.com/input/?source=nav&i=b%3D+x1+%2B+x2*T+%2B+x3*H+%2B+x4*T*H+%2B+x5*T*T+%2B+x6*H*H+%2B+x7*T*T*H+%2B+x8*T*H*H+%2B+x9*T*T*H*H */_“
is incorrect in fact. www.wolframalpha.com generates different formula than used one. Memories of secondary school are sufficient for this task…

@finitespace & @coelner, I think it's time to finish #65 and #77 and go to other matters.

**Pull request merged**
