### PR TITLE
absolute humidity

### PR DESCRIPTION
**Pull request by coelner**
an implementation for absolute humidity

### CODE REVIEW

**Comment by finitespace** [comment]
This pull has conflicts after merging heat index. Please pull the latest version of trunk and resolve the conflicts.

**Comment by finitespace** [comment]
Thanks for adding all of these!

**Comment by finitespace** [comment]
This still has heat index modifications in it but it doesn't conflict. So I am wondering if this merge will cause a duplication. What did you do to fix the pull?

**Comment by coelner** [comment]
I did a rebase with your master (after you accept the pull request) and fix a minor conflict in the keywords. I am not sure, but the github web based view is somehow broken. If you switch to my repo in the correspending branch, you will see a correct web view.

**Comment by finitespace** [comment]
I am hesitant that this will mess up files the way it is displaying the changes. I would like to merge it to a new branch and then back to master to ensure the changes are correct.

**Comment by finitespace** [comment]
There are also compilation issues in this pull request. Again, please make sure you run your code before submitting a pull request. Thanks!

**Comment by finitespace** [comment]
@coelner is there a reason you used double as the return for absHum? Is there an overflow? It is just not consistent with other functions.

**Pull request merged**
